# axios 基础使用

## 为何可以在浏览器端和服务器端都可以使用？

axios 会根据不同的环境来使用不同的适配器。

- 在浏览器环境中运行时，axios 使用 XMLHttpRequest 对象来发送请求。XMLHttpRequest 是浏览器提供的内置对象，用于在浏览器中发起 HTTP 请求。
- 当在 Node.js 环境中运行时，axios 则会使用 Node.js 的 http 或 https 模块来发送请求。

怎么判断环境。可以判断 process.env 是否存在，或者判断 XMLHttpRequest 是否存在。

## 内部是怎么组织拦截器的？

```ts
class InterceptorManager {
  constructor() {
    this.handlers = [];
  }

  use(fulfilled, rejected) {
    this.handlers.push({
      fulfilled: fulfilled,
      rejected: rejected,
    });
    return this.handlers.length - 1;
  }

  eject(id) {
    if (this.handlers[id]) {
      this.handlers[id] = null;
    }
  }

  // 内部方法，用来遍历所有已注册的拦截器并执行它们
  forEach(fn) {
    this.handlers.forEach((h) => {
      if (h !== null) {
        fn(h);
      }
    });
  }
}

// axios里持有两个拦截器管理器实例：一个处理请求拦截器，一个处理响应拦截器
axios.interceptors = {
  request: new InterceptorManager(),
  response: new InterceptorManager(),
};

// 请求处理链，我们将发送请求的逻辑视为最开始的一个“拦截器”
let chain = [dispatchRequest, undefined];

// 将请求拦截器插入到处理链的起始位置
axios.interceptors.request.forEach(function (interceptor) {
  chain.unshift(interceptor.fulfilled, interceptor.rejected);
});

// 将响应拦截器插入到处理链的末尾位置
axios.interceptors.response.forEach(function (interceptor) {
  chain.push(interceptor.fulfilled, interceptor.rejected);
});

// 使用Promise链执行整个处理链
let promise = Promise.resolve(config);
while (chain.length) {
  promise = promise.then(chain.shift(), chain.shift());
}
```

## 拦截器

axios 的拦截器 `xx.use(onFulfilled?: any, onRejected?: any)`，就是 `Promise.then(onFulfilled?: any, onRejected?: any)`

1. **在响应拦截器中，如果 http 状态码是 2xx，那么会走到 success，否则会走到 error**
2. **在响应拦截器中，无论是在成功或者失败回调中进行了 `return Promise.reject()`，那么会走到下一个拦截器的失败回调；**
3. **在响应拦截器中，无论是在成功或者失败回调中进行了 `return Promise.resolve()`，那么会走到下一个拦截器的成功回调；**
4. **在响应拦截器中，在「成功回调」中直接 return data，和 return Promise.resolve(data)，效果相同**
5. **在响应拦截器中，在「失败回调」中直接 return data，会走到下一个拦截器的「成功回调」， return Promise.reject(data)，会走到下一个拦截器的「失败回调」**

```typescript
// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response;
  }, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
    return Promise.reject(error);
  });


// 会走到下个拦截器，并且会走到 成功 的回调
return new Error();

// 什么都不返回，会走到下一个拦截器，并且会走到 成功 的回调，但是下一个拦截器的 response 为 undefined
void;

// 会走到下一个拦截器，并且走到 失败 的回调
return Promise.reject(new Error());

// 会走到下一个拦截器，并且走到 失败 的回调
return Promise.reject({});

```

代码片段解析：

```typescript
const doRetry = async (instance: AxiosInstance, result) => {
  const { retryCount = 0, _alreadyRetryCount = 0 } = result.config;
  const needRetry = retryCount > 0 && retryCount > _alreadyRetryCount;
  if (!needRetry) return result;
  // 给已经重试的次数进行标记
  (result.config as any)._alreadyRetryCount = _alreadyRetryCount + 1;
  return instance(result.config);
};

instance.interceptors.response.use(
  function (response) {
    const { data } = response;
    console.log('retry,success');
    if (data.success === false) {
      return doRetry(instance, response) as any;
    }
    return response;
  },
  function (error: any) {
    console.log('retry,error');
    const result = doRetry(instance, error);
    // 无需重试，抛出错误
    if (result === error) {
      return Promise.reject(error);
    }
    return result;
  },
);
```

> 接口设定：
>
> 1. 接口的 success 为 false
> 2. 接口失败会重试 1 次。

流程分析：

1. 第一次请求进来，接口失败，走到 doRetry，需要重试，所以走到 `return instance(result.config);` ，有 return 需要接着执行 instance(...)，也就是再发送一次请求，此时第一次请求就在等待返回。
2. 第二次请求进来，接口失败，走到 doRetry，不需要重试，走到 `return result;`，
3. 接着走第二个请求的下一个拦截器，直到把所有的拦截器都走完。才能确定第二次请求的最后结果。
4. 此时第一次请求就等到了 Promise 的结果返回。接着走第一次请求的剩下的拦截器。
5. 接口调用的地方拿到接口的最后结果。

是不是可以把 return 去掉？

不可以，如果去掉，第一个请求就会走完所有的拦截器，然后接口调用就拿到了第一次的结果，没得到重试后的结果。

## 怎么取消请求

```ts
import request from 'axios';

export const queryPivotSetting = (data: any, signal?: AbortSignal) => {
  return request({
    url: '/studio_api/subject/D8/setting/v2/query',
    method: 'POST',
    data,
    signal,
  }) as Promise<SubjectSetting>;
};

const abortController = new AbortController();
queryPivotSetting(xxx, abortController.signal);

// 需要取消时
abortController.abort();

// abortController 是一次性的，signal 无法恢复，所以如果需要反复利用，则需要：
import { useEffect, useRef } from 'react';
import { SubjectItem } from '../types';

export const useAbortSignal = (subject: SubjectItem) => {
  const abortController = useRef(new AbortController());

  const abort = () => {
    abortController.current.abort();
    abortController.current = new AbortController();
  };

  useEffect(() => {
    if (subject?.filterParams?.value) {
      abort();
    }
    return () => {
      abortController.current.abort();
    };
  }, [subject?.filterParams?.value]);

  return { signal: abortController.current.signal, abort };
};
```
