# axios 基础使用

## 拦截器

axios 的拦截器 `xx.use(onFulfilled?: any, onRejected?: any)`，就是 `Promise.then(onFulfilled?: any, onRejected?: any)`

1. **在响应拦截器中，如果 http 状态码是 2xx，那么会走到 success，否则会走到 error**
2. **在响应拦截器中，无论是在成功或者失败回调中进行了 `return Promise.reject()`，那么会走到下一个拦截器的失败回调；**
3. **在响应拦截器中，无论是在成功或者失败回调中进行了 `return Promise.resolve()`，那么会走到下一个拦截器的成功回调；**
4. **在响应拦截器中，在「成功回调」中直接 return data，和 return Promise.resolve(data)，效果相同**
5. **在响应拦截器中，在「失败回调」中直接 return data，会走到下一个拦截器的「成功回调」， return Promise.reject(data)，会走到下一个拦截器的「失败回调」**

```typescript
// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response;
  }, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
    return Promise.reject(error);
  });


// 会走到下个拦截器，并且会走到 成功 的回调
return new Error();

// 什么都不返回，会走到下一个拦截器，并且会走到 成功 的回调，但是下一个拦截器的 response 为 undefined
void;

// 会走到下一个拦截器，并且走到 失败 的回调
return Promise.reject(new Error());

// 会走到下一个拦截器，并且走到 失败 的回调
return Promise.reject({});

```

代码片段解析：

```typescript
const doRetry = async (instance: AxiosInstance, result) => {
  const { retryCount = 0, _alreadyRetryCount = 0 } = result.config;
  const needRetry = retryCount > 0 && retryCount > _alreadyRetryCount;
  if (!needRetry) return result;
  // 给已经重试的次数进行标记
  (result.config as any)._alreadyRetryCount = _alreadyRetryCount + 1;
  return instance(result.config);
};

instance.interceptors.response.use(
  function (response) {
    const { data } = response;
    console.log('retry,success');
    if (data.success === false) {
      return doRetry(instance, response) as any;
    }
    return response;
  },
  function (error: any) {
    console.log('retry,error');
    const result = doRetry(instance, error);
    // 无需重试，抛出错误
    if (result === error) {
      return Promise.reject(error);
    }
    return result;
  }
);
```

> 接口设定：
>
> 1. 接口的 success 为 false
> 2. 接口失败会重试 1 次。

流程分析：

1. 第一次请求进来，接口失败，走到 doRetry，需要重试，所以走到 `return instance(result.config);` ，有 return 需要接着执行 instance(...)，也就是再发送一次请求，此时第一次请求就在等待返回。
2. 第二次请求进来，接口失败，走到 doRetry，不需要重试，走到 `return result;`，
3. 接着走第二个请求的下一个拦截器，直到把所有的拦截器都走完。才能确定第二次请求的最后结果。
4. 此时第一次请求就等到了 Promise 的结果返回。接着走第一次请求的剩下的拦截器。
5. 接口调用的地方拿到接口的最后结果。

是不是可以把 return 去掉？
不可以，如果去掉，第一个请求就会走完所有的拦截器，然后接口调用就拿到了第一次的结果，没得到重试后的结果。
